using System.Linq;
using NUnit.Framework;
using UnityEngine;
using System;
using System.Collections.Generic;

namespace Lanternfall.Tests
{
    public class CoreTests
    {
        [Test] public void Movement_RespectsRangeAndWalls(){var g=new GridModel(5,5);for(int x=0;x<5;x++)g.SetFloor(new Vector2Int(x,2));var r=g.Reachable(new Vector2Int(0,2),2,_=>false);Assert.That(r.Contains(new Vector2Int(2,2)));Assert.False(r.Contains(new Vector2Int(3,2)));}
        [Test] public void TurnOrder_RejectsDoubleEnd(){var t=new TurnManager();Assert.True(t.TryBeginEnemyTurn());Assert.False(t.TryBeginEnemyTurn());t.BeginPlayerTurn();Assert.AreEqual(TurnPhase.Player,t.Phase);}
        [Test] public void SkillTargeting_DashRejectsOccupiedTile(){var g=new GridModel(5,5);for(int x=0;x<5;x++)for(int y=0;y<5;y++)g.SetFloor(new Vector2Int(x,y));var p=new PlayerModel{Position=new Vector2Int(2,2)};var set=SkillBook.Targets(g,p,SkillId.LanternDash,q=>q==new Vector2Int(2,3));Assert.False(set.Contains(new Vector2Int(2,3)));Assert.True(set.Contains(new Vector2Int(2,4)));}
        [Test] public void SkillTargeting_BoltHighlightsEnemiesOnly(){var g=new GridModel(5,5);for(int x=0;x<5;x++)for(int y=0;y<5;y++)g.SetFloor(new Vector2Int(x,y));var p=new PlayerModel{Position=new Vector2Int(2,2)};var set=SkillBook.Targets(g,p,SkillId.EmberBolt,q=>q==new Vector2Int(2,4));Assert.That(set.Count,Is.EqualTo(1));Assert.True(set.Contains(new Vector2Int(2,4)));}
        [Test] public void AttackPreview_AshlingShowsAdjacentTiles(){var g=new GridModel(5,5);for(int x=0;x<5;x++)for(int y=0;y<5;y++)g.SetFloor(new Vector2Int(x,y));var e=new EnemyModel(EnemyKind.Ashling,new Vector2Int(2,2));var p=EnemyAI.BuildPreview(e,new Vector2Int(2,3),g);Assert.True(p.Contains(new Vector2Int(2,3)));Assert.False(p.Contains(new Vector2Int(4,4)));}
        [Test] public void RoomGeneration_IsConnectedAndHasSpawns(){var gen=new RoomGenerator();for(int i=1;i<=5;i++){var r=gen.Generate(100+i,i);Assert.True(gen.IsConnected(r.Grid));Assert.True(r.Grid.IsFloor(r.PlayerSpawn));Assert.That(r.EnemySpawns.Count,Is.GreaterThan(0));}}
        [Test] public void WinLoss_ResolveClearly(){var p=new PlayerModel();var dead=new[]{new EnemyModel(EnemyKind.Ashling,Vector2Int.zero)};dead[0].Damage(99);Assert.AreEqual(TurnPhase.Won,GameRules.ResolveOutcome(p,dead,5));p.Damage(99);Assert.AreEqual(TurnPhase.Lost,GameRules.ResolveOutcome(p,dead,1));}
        [Test] public void DifficultyCurve_UsesFixedReadableEncounters(){Assert.That(Enumerable.Range(1,5).Select(BalanceConfig.EnemyCount),Is.EqualTo(new[]{2,2,3,3,1}));Assert.AreEqual(EnemyKind.LanternWarden,BalanceConfig.EnemyFor(5,0));Assert.AreEqual(15,BalanceConfig.EnemyStats(EnemyKind.LanternWarden).health);}
        [Test] public void Recovery_IsCappedAndNeverOverheals(){var p=new PlayerModel();p.Damage(5);Assert.AreEqual(2,p.Recover(BalanceConfig.BetweenRoomRecovery));Assert.AreEqual(9,p.Health);Assert.AreEqual(3,p.Recover(99));Assert.AreEqual(p.MaxHealth,p.Health);}
        [Test] public void Biomes_AllFiveThemesLoadWithStableIdentity(){Assert.AreEqual(5,BiomeCatalog.All.Length);Assert.AreEqual(5,BiomeCatalog.All.Select(b=>b.StableId).Distinct().Count());Assert.That(BiomeCatalog.All.All(b=>!string.IsNullOrWhiteSpace(b.Name)&&!string.IsNullOrWhiteSpace(b.HazardRule)));}
        [Test] public void Biomes_AllMapsStayConnectedAndBossReachable(){var gen=new RoomGenerator();for(int room=1;room<=5;room++){var r=gen.Generate(900+room,room);Assert.True(gen.IsConnected(r.Grid),r.Theme.Name);Assert.AreEqual(BiomeCatalog.ForRoom(room).Id,r.Theme.Id);Assert.AreEqual(5,r.HazardTiles.Count);Assert.True(r.Grid.ShortestPath(r.PlayerSpawn,r.EnemySpawns[0],_=>false).Count>0);}}
        [Test] public void Biomes_EachHazardRuleWorks(){var p=new PlayerModel{Position=Vector2Int.zero};var tile=new HashSet<Vector2Int>{Vector2Int.zero};Assert.AreEqual(2,BiomeRules.MoveRange(p,BiomeCatalog.Get(BiomeId.DrownedNarthex),tile));Assert.AreEqual(2,BiomeRules.SkillRangeBonus(BiomeCatalog.Get(BiomeId.SiltglassObservatory),p.Position,tile,SkillId.EmberBolt));Assert.AreEqual(1,BiomeRules.SkillDamageBonus(BiomeCatalog.Get(BiomeId.SiltglassObservatory),p.Position,tile,SkillId.EmberBolt));Assert.AreEqual(2,BiomeRules.HazardDamage(BiomeCatalog.Get(BiomeId.EmberOssuary),p.Position,tile));Assert.AreEqual(1,BiomeRules.MoveRange(p,BiomeCatalog.Get(BiomeId.GloamOrchard),tile));Assert.AreEqual(2,BiomeRules.HazardDamage(BiomeCatalog.Get(BiomeId.StormvaultFoundry),Vector2Int.right,tile));Assert.AreEqual(0,BiomeRules.HazardDamage(BiomeCatalog.Get(BiomeId.StormvaultFoundry),new Vector2Int(3,3),tile));}
        [Test] public void Biomes_PalettesAndDressingRemainMobileReadable(){var gen=new RoomGenerator();foreach(var b in BiomeCatalog.All)Assert.That(b.TileContrast,Is.GreaterThan(.06f),b.Name);for(int room=1;room<=5;room++){var r=gen.Generate(1200+room,room);int floors=r.Grid.Floors().Count();Assert.LessOrEqual(r.HazardTiles.Count,floors/5);Assert.LessOrEqual(r.PropTiles.Count,floors/10);}}
        [Test] public void Isolation_NoRealtimeActionSystemsWereImported(){string[] banned={"PlayerMotor","Dodge","RealtimeCombat","ActionCombat"};var names=typeof(GridModel).Assembly.GetTypes().Select(t=>t.Name).ToArray();Assert.False(names.Any(n=>banned.Any(b=>n.Contains(b,StringComparison.OrdinalIgnoreCase))));}
    }
}
