using System;
using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using UnityEngine;
using UnityEngine.TestTools;

namespace Lanternfall.Tests
{
    public class CoreTests
    {
        [Test] public void Movement_RespectsRangeAndWalls(){var g=new GridModel(5,5);for(int x=0;x<5;x++)g.SetFloor(new Vector2Int(x,2));var r=g.Reachable(new Vector2Int(0,2),2,_=>false);Assert.That(r.Contains(new Vector2Int(2,2)));Assert.False(r.Contains(new Vector2Int(3,2)));}
        [Test] public void TurnOrder_RejectsDoubleEnd(){var t=new TurnManager();Assert.True(t.TryBeginEnemyTurn());Assert.False(t.TryBeginEnemyTurn());t.BeginPlayerTurn();Assert.AreEqual(TurnPhase.Player,t.Phase);}
        [Test] public void SkillTargeting_DashRejectsOccupiedTile(){var g=FullGrid(5,5);var p=new PlayerModel(PlayerClassId.Vanguard){Position=new Vector2Int(2,2)};var def=SkillBook.Get(SkillId.SunCharge);var set=SkillBook.Targets(g,p,def,q=>q==new Vector2Int(2,3));Assert.False(set.Contains(new Vector2Int(2,3)));Assert.True(set.Contains(new Vector2Int(2,4)));}
        [Test] public void SkillTargeting_BoltHighlightsEnemiesOnly(){var g=FullGrid(5,5);var p=new PlayerModel(PlayerClassId.Cantor){Position=new Vector2Int(2,2)};var set=SkillBook.Targets(g,p,SkillBook.Get(SkillId.EmberBolt),q=>q==new Vector2Int(2,4));Assert.That(set.Count,Is.EqualTo(1));Assert.True(set.Contains(new Vector2Int(2,4)));}
        [Test] public void AttackPreview_AshlingShowsAdjacentTiles(){var g=FullGrid(5,5);var e=new EnemyModel(EnemyKind.Ashling,new Vector2Int(2,2));var p=EnemyAI.BuildPreview(e,new Vector2Int(2,3),g);Assert.True(p.Contains(new Vector2Int(2,3)));Assert.False(p.Contains(new Vector2Int(4,4)));}
        [Test] public void Phase5M_EnemyPreviewsStayOnPlayableTiles(){var gen=new RoomGenerator();for(int room=1;room<=5;room++){var r=gen.Generate(7200+room,room);for(int i=0;i<r.EnemySpawns.Count;i++){var e=new EnemyModel(BalanceConfig.EnemyFor(room,i),r.EnemySpawns[i]);var preview=EnemyAI.BuildPreview(e,r.PlayerSpawn,r.Grid);if(e.Kind!=EnemyKind.GloomArcher)Assert.That(preview.Count,Is.GreaterThan(0),$"room {room} {e.Kind}");Assert.True(preview.All(p=>r.Grid.IsFloor(p)),$"room {room} {e.Kind}");}}}
        [Test] public void RoomGeneration_IsConnectedAndHasSpawns(){var gen=new RoomGenerator();for(int i=1;i<=5;i++){var r=gen.Generate(100+i,i);Assert.True(gen.IsConnected(r.Grid));Assert.True(r.Grid.IsFloor(r.PlayerSpawn));Assert.That(r.EnemySpawns.Count,Is.GreaterThan(0));}}
        [Test] public void WinLoss_ResolveClearly(){var p=new PlayerModel();var dead=new[]{new EnemyModel(EnemyKind.Ashling,Vector2Int.zero)};dead[0].Damage(99);Assert.AreEqual(TurnPhase.Won,GameRules.ResolveOutcome(p,dead,5));p.Damage(99);Assert.AreEqual(TurnPhase.Lost,GameRules.ResolveOutcome(p,dead,1));}
        [Test] public void DifficultyCurve_UsesFixedReadableEncounters(){Assert.That(Enumerable.Range(1,5).Select(BalanceConfig.EnemyCount),Is.EqualTo(new[]{2,2,3,4,1}));Assert.AreEqual(EnemyKind.LanternWarden,BalanceConfig.EnemyFor(5,0));Assert.AreEqual(24,BalanceConfig.EnemyStats(EnemyKind.LanternWarden).health);Assert.AreEqual(6,BalanceConfig.EnemyStats(EnemyKind.StoneSentinel).health);}
        [Test] public void Recovery_IsCappedAndNeverOverheals(){var p=new PlayerModel();p.Damage(5);Assert.AreEqual(0,p.Recover(BalanceConfig.BetweenRoomRecovery));Assert.AreEqual(7,p.Health);Assert.AreEqual(5,p.Recover(99));Assert.AreEqual(p.MaxHealth,p.Health);}
        [Test] public void Phase5N_HealingPickupsSpawnSometimesButNeverInFirstOrBossRoom(){var gen=new RoomGenerator();int room2to4=0,total=0;for(int seed=1000;seed<1100;seed++){for(int room=1;room<=5;room++){var r=gen.Generate(seed,room);if(room==1||room==5)Assert.False(r.HealingPickup.HasValue,$"seed {seed} room {room}");else{total++;if(r.HealingPickup.HasValue)room2to4++;}}}Assert.That(room2to4,Is.GreaterThan(0));Assert.That(room2to4,Is.LessThan(total));}
        [Test] public void Phase5N_HealingPickupsAreReachableAndAvoidBlockedDangerOccupiedTiles(){var gen=new RoomGenerator();int checkedPickups=0;for(int seed=2000;seed<2100;seed++)for(int room=2;room<=4;room++){var r=gen.Generate(seed,room);if(!r.HealingPickup.HasValue)continue;var h=r.HealingPickup.Value;Assert.True(r.Grid.IsFloor(h),$"floor {seed}/{room}");Assert.AreNotEqual(r.PlayerSpawn,h);Assert.False(r.EnemySpawns.Contains(h));Assert.False(r.HazardTiles.Contains(h));Assert.False(r.PropTiles.Contains(h));Assert.That(r.Grid.ShortestPath(r.PlayerSpawn,h,_=>false).Count,Is.GreaterThan(0),$"reachable {seed}/{room}");checkedPickups++;}Assert.That(checkedPickups,Is.GreaterThan(0));}
        [Test] public void Phase5O_RoomBlockersPreserveConnectivityAndCreateLineOfSightChoices(){var gen=new RoomGenerator();int blockers=0;for(int room=1;room<=5;room++){var r=gen.Generate(8100+room,room);Assert.True(gen.IsConnected(r.Grid),$"connected {room}");Assert.True(r.BlockerTiles.All(b=>!r.Grid.IsFloor(b)),$"blocked {room}");Assert.True(r.BlockerTiles.All(b=>b!=r.PlayerSpawn&&!r.EnemySpawns.Contains(b)&&!r.HazardTiles.Contains(b)&&!r.PropTiles.Contains(b)),$"clear {room}");Assert.True(r.EnemySpawns.All(e=>r.Grid.ShortestPath(r.PlayerSpawn,e,_=>false).Count>0),$"reachable enemy {room}");blockers+=r.BlockerTiles.Count;}Assert.That(blockers,Is.GreaterThan(0));}
        [Test] public void Biomes_AllFiveThemesLoadWithStableIdentity(){Assert.AreEqual(5,BiomeCatalog.All.Length);Assert.AreEqual(5,BiomeCatalog.All.Select(b=>b.StableId).Distinct().Count());Assert.That(BiomeCatalog.All.All(b=>!string.IsNullOrWhiteSpace(b.Name)&&!string.IsNullOrWhiteSpace(b.HazardRule)));}
        [Test] public void Biomes_AllMapsStayConnectedAndBossReachable(){var gen=new RoomGenerator();for(int room=1;room<=5;room++){var r=gen.Generate(900+room,room);Assert.True(gen.IsConnected(r.Grid),r.Theme.Name);Assert.AreEqual(BiomeCatalog.ForRoom(room).Id,r.Theme.Id);Assert.AreEqual(5,r.HazardTiles.Count);Assert.True(r.Grid.ShortestPath(r.PlayerSpawn,r.EnemySpawns[0],_=>false).Count>0);}}
        [Test] public void Biomes_EachHazardRuleWorks(){var p=new PlayerModel{Position=Vector2Int.zero};var tile=new HashSet<Vector2Int>{Vector2Int.zero};Assert.AreEqual(2,BiomeRules.MoveRange(p,BiomeCatalog.Get(BiomeId.DrownedNarthex),tile));Assert.AreEqual(1,BiomeRules.SkillRangeBonus(BiomeCatalog.Get(BiomeId.SiltglassObservatory),p.Position,tile,SkillId.EmberBolt));Assert.AreEqual(1,BiomeRules.SkillDamageBonus(BiomeCatalog.Get(BiomeId.SiltglassObservatory),p.Position,tile,SkillId.StraightShot));Assert.AreEqual(2,BiomeRules.HazardDamage(BiomeCatalog.Get(BiomeId.EmberOssuary),p.Position,tile));Assert.AreEqual(2,BiomeRules.MoveRange(p,BiomeCatalog.Get(BiomeId.GloamOrchard),tile));Assert.AreEqual(2,BiomeRules.HazardDamage(BiomeCatalog.Get(BiomeId.StormvaultFoundry),Vector2Int.right,tile));Assert.AreEqual(0,BiomeRules.HazardDamage(BiomeCatalog.Get(BiomeId.StormvaultFoundry),new Vector2Int(3,3),tile));}
        [Test] public void Biomes_PalettesAndDressingRemainMobileReadable(){var gen=new RoomGenerator();foreach(var b in BiomeCatalog.All)Assert.That(b.TileContrast,Is.GreaterThan(.06f),b.Name);for(int room=1;room<=5;room++){var r=gen.Generate(1200+room,room);int floors=r.Grid.Floors().Count();Assert.LessOrEqual(r.HazardTiles.Count,floors/5);Assert.LessOrEqual(r.PropTiles.Count,floors/10);}}
        [Test] public void Phase5F_TileStatePaletteKeepsStrongReadableContrast(){foreach(var b in BiomeCatalog.All){var floor=VisualReadability.TileColor(b,TileVisualState.Floor);Assert.That(VisualReadability.Contrast(floor,VisualReadability.TileColor(b,TileVisualState.MoveTarget)),Is.GreaterThan(.18f),b.Name+" move");Assert.That(VisualReadability.Contrast(floor,VisualReadability.TileColor(b,TileVisualState.SkillTarget)),Is.GreaterThan(.18f),b.Name+" skill");Assert.That(VisualReadability.Contrast(floor,VisualReadability.TileColor(b,TileVisualState.EnemyPreview)),Is.GreaterThan(.08f),b.Name+" danger");Assert.That(VisualReadability.Contrast(floor,VisualReadability.TileColor(b,TileVisualState.ArmedHazard)),Is.GreaterThan(.10f),b.Name+" hazard");}}
        [Test] public void Phase6I_BiomeHazardsUseDistinctAuthoredIcons(){var cells=BiomeCatalog.All.Select(b=>IconLanguage.AtlasCell(IconLanguage.ForHazard(b.Hazard))).ToArray();Assert.AreEqual(5,cells.Distinct().Count());Assert.True(cells.All(c=>c>=0&&c<AuthoredArt.IconColumns*AuthoredArt.IconRows));}
        [Test] public void Isolation_NoRealtimeActionSystemsWereImported(){string[] banned={"PlayerMotor","Dodge","RealtimeCombat","ActionCombat"};var names=typeof(GridModel).Assembly.GetTypes().Select(t=>t.Name).ToArray();Assert.False(names.Any(n=>banned.Any(b=>n.Contains(b,StringComparison.OrdinalIgnoreCase))));}
        [Test] public void Classes_EachClassHasThreeUsableOriginalSkills(){foreach(var cls in ClassCatalog.All){var skills=SkillBook.ForClass(cls.id);Assert.AreEqual(3,skills.Length,cls.name);Assert.True(skills.All(s=>s.ApCost>0&&s.Range>=0&&!string.IsNullOrWhiteSpace(s.Hint)));}}
        [Test] public void Phase5K_ClassBiomeAndRewardTextStayReadable(){Assert.True(ClassCatalog.All.All(c=>!string.IsNullOrWhiteSpace(c.name)&&!string.IsNullOrWhiteSpace(c.title)&&c.description.Length>=24));Assert.True(BiomeCatalog.All.All(b=>!string.IsNullOrWhiteSpace(b.HazardName)&&b.HazardRule.Length>=18));Assert.True(RewardCatalog.LabelsReadable);Assert.True(RewardCatalog.All.All(r=>r.Effect.Contains("+")&&(r.Effect.Contains("HP")||r.Effect.Contains("damage")||r.Effect.Contains("MP"))));}
        [Test] public void Phase5M_RewardCardsShowNameExactEffectAndSafeLineLengths(){for(int i=0;i<RewardCatalog.All.Length;i++){var r=RewardCatalog.Get(i);var label=RewardCatalog.WebGLCardLabel(i);Assert.That(label,Does.Contain(r.Name));Assert.That(label,Does.Contain(r.Effect));Assert.That(label,Does.Contain(r.Detail));Assert.True(label.Split('\n').All(line=>line.Length<=24),label);Assert.False(label.Contains("EMBER\n"));Assert.False(label.Contains("FLAME\n"));}}
        [Test] public void Phase5M_RoomScalingIncreasesThreatByDepth(){var early=new EnemyModel(EnemyKind.Ashling,Vector2Int.zero);BalanceConfig.ApplyRoomScaling(early,1);var late=new EnemyModel(EnemyKind.Ashling,Vector2Int.zero);BalanceConfig.ApplyRoomScaling(late,4);Assert.Greater(late.MaxHealth,early.MaxHealth);Assert.Greater(late.AttackDamage,early.AttackDamage);Assert.GreaterOrEqual(late.MoveRange,early.MoveRange);}
        [Test] public void Phase5M_BossIsStrongerAndEscalatesPreviewAtLowHealth(){var g=FullGrid(9,9);var boss=new EnemyModel(EnemyKind.LanternWarden,new Vector2Int(4,4));BalanceConfig.ApplyRoomScaling(boss,5);Assert.Greater(boss.MaxHealth,BalanceConfig.EnemyStats(EnemyKind.StoneSentinel).health*3);Assert.Greater(boss.AttackDamage,BalanceConfig.EnemyStats(EnemyKind.StoneSentinel).damage);var normal=EnemyAI.BuildPreview(boss,Vector2Int.zero,g).Count;boss.Damage(boss.MaxHealth/2+1);Assert.Greater(EnemyAI.BuildPreview(boss,Vector2Int.zero,g).Count,normal);}
        [Test] public void Phase5O_BossPhasesChangeIntentAndThreatShape(){var g=FullGrid(9,9);var boss=new EnemyModel(EnemyKind.LanternWarden,new Vector2Int(4,4));BalanceConfig.ApplyRoomScaling(boss,5);EnemyAI.AssignIntent(boss,new Vector2Int(4,1),g);Assert.AreEqual(1,EnemyAI.BossPhase(boss));Assert.AreEqual(ThreatKind.HP,boss.Threat);var phase1=boss.DelayedPreview.Count;boss.Damage(boss.MaxHealth/2);EnemyAI.AssignIntent(boss,new Vector2Int(4,1),g);Assert.AreEqual(2,EnemyAI.BossPhase(boss));Assert.AreEqual(ThreatKind.Mixed,boss.Threat);Assert.Greater(boss.DelayedPreview.Count,phase1);boss.Damage(boss.MaxHealth);EnemyAI.AssignIntent(boss,new Vector2Int(4,1),g);Assert.AreEqual(3,EnemyAI.BossPhase(boss));Assert.That(boss.IntentLabel,Does.Contain("HEAVY").And.Contain("BLAST"));Assert.Greater(boss.Preview.Count,phase1);}
        [Test] public void Phase5Q_BossPhaseTwoIsAnnouncedAndAddsVisibleShield(){var go=new GameObject("BossPhase2");var game=go.AddComponent<LanternfallGame>();game.StartRun(9400);for(int i=0;i<4;i++){game.Turns.ShowReward();game.ChooseReward(0);}var boss=game.Enemies.Single(e=>e.Kind==EnemyKind.LanternWarden);boss.Damage(boss.MaxHealth/2);var method=typeof(LanternfallGame).GetMethod("TryAnnounceBossPhase",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic);Assert.True((bool)method.Invoke(game,new object[]{boss}));Assert.AreEqual(2,boss.BossPhaseAnnounced);Assert.That(boss.Shield,Is.GreaterThanOrEqualTo(4));Assert.That(game.Message,Does.Contain("PHASE TWO").And.Contain("awakens").And.Contain("attack pattern"));UnityEngine.Object.DestroyImmediate(go);}
        [Test] public void Phase5Q_BossDelayedPressureDoesNotHideLethalHpDamage(){var go=new GameObject("BossNoHiddenBurst");var game=go.AddComponent<LanternfallGame>();game.StartRun(9401);for(int i=0;i<4;i++){game.Turns.ShowReward();game.ChooseReward(0);}var boss=game.Enemies.Single(e=>e.Kind==EnemyKind.LanternWarden);boss.Damage(boss.MaxHealth);boss.Health=Mathf.Max(1,boss.MaxHealth/4);EnemyAI.AssignIntent(boss,game.Player.Position,game.Grid);int hp=game.Player.Health;typeof(LanternfallGame).GetMethod("ApplyIntentPressure",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(game,new object[]{boss});Assert.AreEqual(hp,game.Player.Health);Assert.That(game.PendingApDrain,Is.GreaterThan(0));UnityEngine.Object.DestroyImmediate(go);}
        [Test] public void Phase5Q_BossThreatHudExplainsHeavyDamageTimingAndPhase(){var go=new GameObject("BossThreatHud");var game=go.AddComponent<LanternfallGame>();game.StartRun(9402);for(int i=0;i<4;i++){game.Turns.ShowReward();game.ChooseReward(0);}var boss=game.Enemies.Single(e=>e.Kind==EnemyKind.LanternWarden);boss.Position=game.Grid.Neighbors(game.Player.Position).First();boss.Damage(boss.MaxHealth);boss.Health=Mathf.Max(1,boss.MaxHealth/4);game.RefreshPreviews();var tile=boss.Preview.Contains(game.Player.Position)?game.Player.Position:boss.Preview.First();var detail=game.ThreatDetailAt(tile);Assert.That(detail,Does.Contain("HEAVY").Or.Contain("BLAST"));Assert.That(detail,Does.Contain("now").Or.Contain("next turn"));Assert.That(detail,Does.Contain("Phase 3"));UnityEngine.Object.DestroyImmediate(go);}
        [Test] public void Phase5O_EnemyIntentsExposeHpApAndMpPressure(){var g=FullGrid(7,7);var player=new Vector2Int(3,3);var kinds=new[]{EnemyKind.Ashling,EnemyKind.GloomArcher,EnemyKind.StoneSentinel};var threats=kinds.Select(k=>{var e=new EnemyModel(k,new Vector2Int(3,1));EnemyAI.AssignIntent(e,player,g);Assert.False(string.IsNullOrWhiteSpace(e.IntentLabel));Assert.That(e.DelayedPreview.Count,Is.GreaterThan(0),k.ToString());return e.Threat;}).ToArray();Assert.Contains(ThreatKind.HP,threats);Assert.Contains(ThreatKind.AP,threats);Assert.Contains(ThreatKind.MP,threats);}
        [Test] public void Phase5O_LineOfSightBlockersMatterForRangedTargeting(){var g=FullGrid(5,5);g.SetFloor(new Vector2Int(2,2),false);var p=new PlayerModel(PlayerClassId.Wayfinder){Position=new Vector2Int(0,2)};Assert.False(SkillBook.HasLineOfSight(g,p.Position,new Vector2Int(4,2)));g.SetFloor(new Vector2Int(2,2));Assert.True(SkillBook.HasLineOfSight(g,p.Position,new Vector2Int(4,2)));}
        [Test] public void Phase5P_ThreatMarkersStayCompactAndAvoidRepeatedApMpText(){foreach(ThreatKind t in Enum.GetValues(typeof(ThreatKind))){var marker=ThreatReadability.TileMarker(t);Assert.True(ThreatReadability.IsCompactTileMarker(marker),$"{t} {marker}");}var g=FullGrid(7,7);var player=new Vector2Int(3,3);foreach(EnemyKind k in Enum.GetValues(typeof(EnemyKind))){var e=new EnemyModel(k,new Vector2Int(3,1));EnemyAI.AssignIntent(e,player,g);Assert.That(ThreatReadability.EnemyBadge(e).Length,Is.LessThanOrEqualTo(5),k.ToString());}}
        [Test] public void Phase5P_ThreatDetailsMoveToHudFriendlyText(){var go=new GameObject("ThreatHud");var game=go.AddComponent<LanternfallGame>();game.StartRun(5050);var enemy=game.Enemies.First();enemy.Position=game.Grid.Neighbors(game.Player.Position).First();EnemyAI.AssignIntent(enemy,game.Player.Position,game.Grid);game.RefreshPreviews();var tile=enemy.Preview.Concat(enemy.DelayedPreview).First();var detail=game.ThreatDetailAt(tile);Assert.That(detail,Does.Contain(LanternfallGame.NameOf(enemy.Kind)));Assert.That(detail,Does.Contain("now").Or.Contain("next turn"));UnityEngine.Object.DestroyImmediate(go);}
        [Test] public void Phase5P_ImmediateAndDelayedDangerColorsRemainDistinct(){var theme=BiomeCatalog.Get(BiomeId.StormvaultFoundry);var red=VisualReadability.TileColor(theme,TileVisualState.EnemyPreview);var purple=ThreatReadability.TileMarkerColor(ThreatKind.AP);Assert.That(VisualReadability.Contrast(red,purple),Is.GreaterThan(.12f));Assert.That(VisualReadability.Contrast(red,VisualReadability.TileColor(theme,TileVisualState.SkillTarget)),Is.GreaterThan(.12f));}
        [Test] public void Phase5M_EnemiesRepositionToPressureMovement(){var g=FullGrid(7,7);var e=new EnemyModel(EnemyKind.Ashling,new Vector2Int(1,1));var player=new Vector2Int(5,5);var next=EnemyAI.ChooseReposition(e,player,g,_=>false);Assert.AreNotEqual(e.Position,next);Assert.Less(Mathf.Abs(next.x-player.x)+Mathf.Abs(next.y-player.y),Mathf.Abs(e.Position.x-player.x)+Mathf.Abs(e.Position.y-player.y));}
        [Test] public void Phase5Q_NormalEnemiesDoNotIdleWhenUsefulRepositionExists(){var g=FullGrid(9,9);var player=new Vector2Int(7,7);foreach(var kind in new[]{EnemyKind.Ashling,EnemyKind.StoneSentinel}){var e=new EnemyModel(kind,new Vector2Int(1,1));var next=EnemyAI.ChooseReposition(e,player,g,_=>false);Assert.AreNotEqual(e.Position,next,kind.ToString());Assert.Less(Mathf.Abs(next.x-player.x)+Mathf.Abs(next.y-player.y),Mathf.Abs(e.Position.x-player.x)+Mathf.Abs(e.Position.y-player.y),kind.ToString());}}
        [Test] public void Phase5Q_NormalEnemiesAvoidMeaninglessLeftMoveWhenBetterPressureExists(){var g=FullGrid(9,9);var player=new Vector2Int(6,4);var e=new EnemyModel(EnemyKind.Ashling,new Vector2Int(3,4));var next=EnemyAI.ChooseReposition(e,player,g,_=>false);Assert.GreaterOrEqual(next.x,e.Position.x);Assert.Less(Mathf.Abs(next.x-player.x)+Mathf.Abs(next.y-player.y),Mathf.Abs(e.Position.x-player.x)+Mathf.Abs(e.Position.y-player.y));}
        [Test] public void Phase5Q_RangedEnemiesTryToGainClearLineOfSight(){var g=FullGrid(9,9);g.SetFloor(new Vector2Int(4,4),false);var player=new Vector2Int(7,4);var e=new EnemyModel(EnemyKind.GloomArcher,new Vector2Int(2,4)){MoveRange=5};var next=EnemyAI.ChooseReposition(e,player,g,p=>false);Assert.AreNotEqual(e.Position,next);Assert.True((next.x==player.x||next.y==player.y)&&SkillBook.HasLineOfSight(g,next,player),$"{next}");}
        [Test] public void Phase5Q4_SeededEnemyTurnMovesNormalEnemiesWhenOutOfThreatRange(){var go=new GameObject("SeededEnemyMove");var game=go.AddComponent<LanternfallGame>();game.StartRun(9604);var floors=game.Grid.Floors().ToList();game.Player.Position=floors.OrderBy(p=>p.x+p.y).First();game.Enemies.Clear();var start=floors.Where(p=>p!=game.Player.Position&&Mathf.Abs(p.x-game.Player.Position.x)+Mathf.Abs(p.y-game.Player.Position.y)>4).OrderByDescending(p=>Mathf.Abs(p.x-game.Player.Position.x)+Mathf.Abs(p.y-game.Player.Position.y)).First();var enemy=new EnemyModel(EnemyKind.Ashling,start);game.Enemies.Add(enemy);game.RefreshPreviews();Assert.False(enemy.Preview.Contains(game.Player.Position));Assert.False(enemy.DelayedPreview.Contains(game.Player.Position));game.Turns.TryBeginEnemyTurn();var turn=(System.Collections.IEnumerator)typeof(LanternfallGame).GetMethod("EnemyTurn",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(game,null);while(turn.MoveNext()){}Assert.AreNotEqual(start,enemy.Position);Assert.Less(Mathf.Abs(enemy.Position.x-game.Player.Position.x)+Mathf.Abs(enemy.Position.y-game.Player.Position.y),Mathf.Abs(start.x-game.Player.Position.x)+Mathf.Abs(start.y-game.Player.Position.y));UnityEngine.Object.DestroyImmediate(go);}
        [Test] public void Phase6A_AshlingPrefersMediumRangeOverNeedlessMelee(){var g=FullGrid(9,9);var player=new Vector2Int(4,4);var e=new EnemyModel(EnemyKind.Ashling,new Vector2Int(4,1)){MoveRange=3};var next=EnemyAI.ChooseReposition(e,player,g,_=>false,p=>p==new Vector2Int(4,3));int d=Mathf.Abs(next.x-player.x)+Mathf.Abs(next.y-player.y);Assert.That(d,Is.InRange(2,3));Assert.AreNotEqual(new Vector2Int(4,3),next);}
        [Test] public void Phase6A_ArcherRetreatsFromMeleeAndKeepsLineOfSight(){var g=FullGrid(9,9);var player=new Vector2Int(4,4);var e=new EnemyModel(EnemyKind.GloomArcher,new Vector2Int(4,5)){MoveRange=3};var next=EnemyAI.ChooseReposition(e,player,g,_=>false);Assert.Greater(Mathf.Abs(next.x-player.x)+Mathf.Abs(next.y-player.y),1);Assert.True((next.x==player.x||next.y==player.y)&&SkillBook.HasLineOfSight(g,next,player));}
        [Test] public void Phase6A_SentinelProtectsRangedAllyOnLine(){var g=FullGrid(9,9);var player=new Vector2Int(4,7);var archer=new EnemyModel(EnemyKind.GloomArcher,new Vector2Int(4,2));var sentinel=new EnemyModel(EnemyKind.StoneSentinel,new Vector2Int(2,5)){MoveRange=4};var next=EnemyAI.ChooseReposition(sentinel,player,g,_=>false,null,new[]{sentinel,archer});Assert.AreEqual(4,next.x);Assert.That(next.y,Is.InRange(3,6));}
        [Test] public void Phase6A_BossPhaseTwoHasPresentationAndSingleUpgradeMessage(){var go=new GameObject("BossPhaseTwoPresentation");var game=go.AddComponent<LanternfallGame>();game.StartRun(9700);for(int i=0;i<4;i++){game.Turns.ShowReward();game.ChooseReward(0);}var boss=game.Enemies.Single(e=>e.Kind==EnemyKind.LanternWarden);boss.Damage(boss.MaxHealth/2);var method=typeof(LanternfallGame).GetMethod("TryAnnounceBossPhase",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic);Assert.True((bool)method.Invoke(game,new object[]{boss}));Assert.AreEqual("PHASE TWO",game.BossPhaseBanner);Assert.True(game.BossPhasePresentationActive);Assert.That(game.Message,Does.Contain("The Lantern Warden awakens").And.Contain("New attack pattern"));Assert.That(game.Message,Does.Not.Contain("damage increased"));UnityEngine.Object.DestroyImmediate(go);}
        [Test] public void Phase5Q_NormalThreatKindsStillExposeApMpPressure(){var g=FullGrid(7,7);var player=new Vector2Int(3,3);var archer=new EnemyModel(EnemyKind.GloomArcher,new Vector2Int(3,1));EnemyAI.AssignIntent(archer,player,g);Assert.AreEqual(ThreatKind.AP,archer.Threat);Assert.That(archer.DelayedPreview.Count,Is.GreaterThan(0));var sentinel=new EnemyModel(EnemyKind.StoneSentinel,new Vector2Int(2,3));EnemyAI.AssignIntent(sentinel,player,g);Assert.AreEqual(ThreatKind.MP,sentinel.Threat);Assert.True(sentinel.Preview.Contains(player)||sentinel.DelayedPreview.Contains(player));}
        [Test] public void Phase6I_ClassesAndEnemiesUseAuthoredTokenCells(){var classCells=ClassCatalog.All.Select(c=>AuthoredUnits.Cell(c.id)).ToArray();var enemyCells=Enum.GetValues(typeof(EnemyKind)).Cast<EnemyKind>().Select(AuthoredUnits.Cell).ToArray();Assert.AreEqual(classCells.Length,classCells.Distinct().Count());Assert.AreEqual(enemyCells.Length,enemyCells.Distinct().Count());foreach(var cls in ClassCatalog.All)Assert.That(VisualReadability.Contrast(Color.black,VisualReadability.ClassAccent(cls.id)),Is.GreaterThan(.20f),cls.name);foreach(EnemyKind kind in Enum.GetValues(typeof(EnemyKind)))Assert.That(VisualReadability.Contrast(Color.black,VisualReadability.EnemyColor(kind)),Is.GreaterThan(.18f),kind.ToString());}
        [Test] public void Phase6C_IconFoundationCoversEveryRequestedMeaningWithStableUniqueIds(){Assert.That(IconLanguage.All.Length,Is.GreaterThanOrEqualTo(20));var descriptions=IconLanguage.All.Select(IconLanguage.Describe).ToArray();Assert.AreEqual(IconLanguage.All.Length,descriptions.Select(d=>d.StableId).Distinct().Count());Assert.True(descriptions.All(d=>!string.IsNullOrWhiteSpace(d.Meaning)&&VisualReadability.Contrast(Color.black,d.Color)>.12f));foreach(HazardKind h in Enum.GetValues(typeof(HazardKind)))Assert.That(IconLanguage.Describe(IconLanguage.ForHazard(h)).StableId,Does.StartWith("hazard."));Assert.AreEqual(VisualIcon.ActionDrain,IconLanguage.ForThreat(ThreatKind.AP));Assert.AreEqual(VisualIcon.MovementDrain,IconLanguage.ForThreat(ThreatKind.MP));}
        [Test] public void Phase6D_AuthoredAtlasMapsEveryIconAndUiSkinToValidCells(){Assert.AreEqual(27,IconLanguage.All.Length);Assert.True(IconLanguage.All.All(i=>IconLanguage.AtlasCell(i)>=0&&IconLanguage.AtlasCell(i)<25));foreach(UiSkin skin in Enum.GetValues(typeof(UiSkin)))Assert.That((int)skin,Is.InRange(0,8));for(int i=0;i<25;i++){var uv=AuthoredArt.CellUv(i,5,5);Assert.That(uv.xMin,Is.GreaterThanOrEqualTo(0));Assert.That(uv.yMin,Is.GreaterThanOrEqualTo(0));Assert.That(uv.xMax,Is.LessThanOrEqualTo(1));Assert.That(uv.yMax,Is.LessThanOrEqualTo(1));}Assert.AreEqual("UI/phase6d_icon_atlas",AuthoredArt.IconAtlasResource);Assert.AreEqual("UI/phase6d_ui_atlas",AuthoredArt.UiAtlasResource);}
        [Test] public void Phase6E_AuthoredUnitsCoverEveryClassEnemyAndBossState(){var playerCells=Enum.GetValues(typeof(PlayerClassId)).Cast<PlayerClassId>().Select(AuthoredUnits.Cell).ToArray();var enemyCells=Enum.GetValues(typeof(EnemyKind)).Cast<EnemyKind>().Select(AuthoredUnits.Cell).ToArray();Assert.AreEqual(5,playerCells.Distinct().Count());Assert.AreEqual(4,enemyCells.Distinct().Count());Assert.True(playerCells.Concat(enemyCells).All(c=>c>=0&&c<9));Assert.AreEqual(9,playerCells.Concat(enemyCells).Distinct().Count());Assert.AreEqual("Units/phase6e_unit_atlas",AuthoredUnits.AtlasResource);Assert.AreNotEqual(AuthoredUnits.Tint(false),AuthoredUnits.Tint(true));var boss=new EnemyModel(EnemyKind.LanternWarden,Vector2Int.zero);Assert.False(AuthoredUnits.IsOverchargedBoss(boss));boss.Health=Mathf.FloorToInt(boss.MaxHealth*.6f);Assert.True(AuthoredUnits.IsOverchargedBoss(boss));}
        [Test] public void Phase6F_AuthoredBiomesCoverEveryBiomeAndAtlasCell(){var resources=Enum.GetValues(typeof(BiomeId)).Cast<BiomeId>().Select(AuthoredBiomes.Resource).ToArray();Assert.AreEqual(5,resources.Distinct().Count());Assert.True(resources.All(r=>r.StartsWith("Biomes/phase6f_")));Assert.AreEqual(3,AuthoredBiomes.Columns);Assert.AreEqual(3,AuthoredBiomes.Rows);Assert.True(Enum.GetValues(typeof(BiomeArtCell)).Cast<BiomeArtCell>().All(c=>(int)c>=0&&(int)c<9));Assert.AreNotEqual(AuthoredBiomes.PropCell(Vector2Int.zero),AuthoredBiomes.PropCell(Vector2Int.right));}
        [Test] public void Phase6G_ReducedMotionPreferenceIsPersistentAndShortensEffects(){bool before=PresentationMotion.Reduced;try{PresentationMotion.Reduced=false;Assert.AreEqual(.4f,PresentationMotion.Duration(.4f),.001f);PresentationMotion.Reduced=true;Assert.True(PresentationMotion.Reduced);Assert.AreEqual(.06f,PresentationMotion.Duration(.4f),.001f);Assert.That(PresentationMotion.Ease(.5f),Is.GreaterThan(.5f));}finally{PresentationMotion.Reduced=before;}}
        [Test] public void Phase6G_CombatEffectLanguageCoversActionFamilies(){Assert.AreEqual(CombatEffectCue.Spear,CombatEffectLanguage.ForMessage("Spear Thrust: 3 damage"));Assert.AreEqual(CombatEffectCue.Projectile,CombatEffectLanguage.ForMessage("Straight Shot: 3 damage"));Assert.AreEqual(CombatEffectCue.Fire,CombatEffectLanguage.ForMessage("Cinder Bloom burns 2 tiles"));Assert.AreEqual(CombatEffectCue.Prism,CombatEffectLanguage.ForMessage("Piercing Prism: 5 damage"));Assert.AreEqual(CombatEffectCue.Shadow,CombatEffectLanguage.ForMessage("Shadow Swap: positions traded"));Assert.AreEqual(CombatEffectCue.Root,CombatEffectLanguage.ForMessage("Lens Trap: target rooted"));Assert.AreEqual(CombatEffectCue.DrainAP,CombatEffectLanguage.ForMessage("drains AP"));Assert.AreEqual(CombatEffectCue.DrainMP,CombatEffectLanguage.ForMessage("drains MP"));Assert.AreEqual(CombatEffectCue.Heal,CombatEffectLanguage.ForMessage("healing pickup heals 3"));Assert.AreNotEqual(CombatEffectLanguage.Color(CombatEffectCue.Fire),CombatEffectLanguage.Color(CombatEffectCue.Prism));}
        [Test] public void Phase6H_PropsAreSparseAndAnchoredToBoardStructure(){var gen=new RoomGenerator();int total=0;for(int seed=9000;seed<9040;seed++)for(int room=1;room<=5;room++){var r=gen.Generate(seed,room);Assert.LessOrEqual(r.PropTiles.Count,room>=4?2:1,$"{seed}/{room}");Assert.True(r.PropTiles.All(p=>RoomGenerator.IsPropAnchor(r.Grid,p)),$"anchor {seed}/{room}");total+=r.PropTiles.Count;}Assert.That(total,Is.GreaterThan(0));}
        [Test] public void Phase6H_EnvironmentIsQuieterThanTacticalLayersAndUnitsFillTiles(){foreach(var theme in BiomeCatalog.All){var quiet=VisualReadability.QuietEnvironmentOverlay(theme);float qMin=Mathf.Min(quiet.r,Mathf.Min(quiet.g,quiet.b)),cMin=Mathf.Min(theme.Floor.r,Mathf.Min(theme.Floor.g,theme.Floor.b));Assert.That(quiet.a,Is.InRange(.24f,.66f));Assert.LessOrEqual(quiet.maxColorComponent-qMin,theme.Floor.maxColorComponent-cMin);Assert.GreaterOrEqual(VisualReadability.TacticalOverlayAlpha(TileVisualState.EnemyPreview),quiet.a);}Assert.AreEqual(.42f,VisualReadability.EnvironmentTextureTint(BiomeId.SiltglassObservatory).r,.001f);Assert.Greater(VisualReadability.UnitTokenScale(true,false),VisualReadability.UnitTokenScale(false,false));Assert.Greater(VisualReadability.UnitTokenScale(false,true),VisualReadability.UnitTokenScale(true,false));Assert.LessOrEqual(VisualReadability.UnitTokenScale(false,true),.99f);}
        [Test] public void Phase6I_FirstTimeInstructionsCoverTheFullTacticalScan(){var text=string.Join(" ",LanternfallGame.HowToPlayLines);Assert.That(text,Does.Contain("framed hero"));Assert.That(text,Does.Contain("End Turn"));Assert.That(text,Does.Contain("Red hits now"));Assert.That(text,Does.Contain("AP/MP"));Assert.That(text,Does.Contain("not gold"));Assert.That(text,Does.Contain("blessing"));Assert.That(text,Does.Contain("Phase 2"));}
        [Test] public void Phase5E_SkillHintsStayConciseForWebGLButtons(){Assert.True(SkillBook.All.All(s=>s.Hint.Length<=24&&!s.Hint.Contains(" AP")),string.Join(", ",SkillBook.All.Where(s=>s.Hint.Length>24||s.Hint.Contains(" AP")).Select(s=>s.Name)));}
        [Test] public void Skills_AllHavePossibleTargetsOnReadableBoard(){var g=FullGrid(7,7);foreach(var cls in ClassCatalog.All){var p=new PlayerModel(cls.id){Position=new Vector2Int(3,3)};foreach(var s in SkillBook.ForClass(cls.id)){var target=s.Effect==SkillEffect.DiagonalMove?new Vector2Int(4,4):new Vector2Int(3,4);var set=SkillBook.Targets(g,p,s,q=>q==target);Assert.That(set.Count,Is.GreaterThan(0),$"{cls.name} {s.Name}");}}}
        [Test] public void Phase5D_ClassStatsStayDistinctButValid(){Assert.AreEqual(15,new PlayerModel(PlayerClassId.Vanguard).MaxHealth);Assert.AreEqual(11,new PlayerModel(PlayerClassId.Gloamstep).MaxHealth);Assert.AreEqual(7,new PlayerModel(PlayerClassId.Artificer).MaxActionPoints);Assert.AreEqual(4,new PlayerModel(PlayerClassId.Gloamstep).MoveRange);}
        [Test] public void LineOfSight_BlocksInvalidLineAttacks(){var g=new GridModel(5,5);g.SetFloor(new Vector2Int(0,2));g.SetFloor(new Vector2Int(1,2));g.SetFloor(new Vector2Int(3,2));g.SetFloor(new Vector2Int(4,2));Assert.False(SkillBook.HasLineOfSight(g,new Vector2Int(0,2),new Vector2Int(4,2)));g.SetFloor(new Vector2Int(2,2));Assert.True(SkillBook.HasLineOfSight(g,new Vector2Int(0,2),new Vector2Int(4,2)));}
        [Test] public void TacticalEffects_StatusesApplyAndExpire(){var e=new EnemyModel(EnemyKind.Ashling,Vector2Int.zero){BurnTurns=2,RootTurns=1,MarkedTurns=1};e.TickStatuses();Assert.AreEqual(1,e.BurnTurns);Assert.AreEqual(0,e.RootTurns);Assert.AreEqual(0,e.MarkedTurns);Assert.Less(e.Health,e.MaxHealth);}
        [Test] public void Phase6I1_SkillSelectionAlwaysExplainsFullRangeWhenNoTargetExists(){var go=new GameObject("RangePreview");var game=go.AddComponent<LanternfallGame>();game.StartRun(10601);game.Enemies.Clear();game.SelectSkill(SkillId.EmberBolt);Assert.AreEqual(0,game.ValidTargets.Count);Assert.That(game.SkillRangeTiles.Count,Is.GreaterThan(0));Assert.That(game.BlockedSkillTiles.Count,Is.GreaterThan(0));Assert.That(game.OutOfRangeSkillTiles.Count,Is.GreaterThan(0));Assert.That(game.Message,Does.Contain("no legal target").And.Contain("range"));UnityEngine.Object.DestroyImmediate(go);}
        [Test] public void Phase6I1_HazardTraversalCostsMatchDesignAndRemainPassable(){var position=new Vector2Int(2,0);var hazards=new HashSet<Vector2Int>{position};var expected=new Dictionary<HazardKind,int>{{HazardKind.ShallowWater,2},{HazardKind.Prism,1},{HazardKind.EmberVent,4},{HazardKind.GraspingRoots,2},{HazardKind.ChargedFloor,3}};foreach(var theme in BiomeCatalog.All)Assert.AreEqual(expected[theme.Hazard],BiomeRules.EnemyTraversalCost(theme,position,hazards),theme.Name);var g=new GridModel(5,1);for(int x=0;x<5;x++)g.SetFloor(new Vector2Int(x,0));Assert.AreEqual(7,g.WeightedDistance(Vector2Int.zero,new Vector2Int(4,0),_=>false,p=>p==position?4:1));}
        [Test] public void Phase6I1_EnemiesDoNotReverseOntoTheirPreviousTile(){var g=FullGrid(9,9);var player=new Vector2Int(7,4);var e=new EnemyModel(EnemyKind.Ashling,new Vector2Int(3,4)){PreviousPosition=new Vector2Int(2,4),MoveRange=2};var next=EnemyAI.ChooseReposition(e,player,g,_=>false);Assert.AreNotEqual(e.PreviousPosition.Value,next);Assert.Less(Mathf.Abs(next.x-player.x)+Mathf.Abs(next.y-player.y),Mathf.Abs(e.Position.x-player.x)+Mathf.Abs(e.Position.y-player.y));}
        [Test] public void Phase6I1_FourTurnPathDoesNotOscillateBetweenTwoTiles(){var g=FullGrid(9,9);var player=new Vector2Int(7,7);var e=new EnemyModel(EnemyKind.StoneSentinel,new Vector2Int(1,1)){MoveRange=2};var positions=new List<Vector2Int>{e.Position};for(int turn=0;turn<4;turn++){var before=e.Position;var next=EnemyAI.ChooseReposition(e,player,g,_=>false,null,new[]{e});if(positions.Count>=2)Assert.False(next==positions[positions.Count-2]&&next!=before,$"bounce {before}->{next}");e.PreviousPosition=before;e.CommittedDestination=next;e.Position=next;positions.Add(next);}}
        [Test] public void Phase6I1_AdjacentEnemyAttacksEvenWhenStandingOnHazard(){var go=new GameObject("AdjacentHazardAttack");var game=go.AddComponent<LanternfallGame>();game.StartRun(10602);var adjacent=game.Grid.Neighbors(game.Player.Position).First();game.Enemies.Clear();var enemy=new EnemyModel(EnemyKind.Ashling,adjacent);game.Enemies.Add(enemy);game.HazardTiles.Add(adjacent);game.RefreshPreviews();int hp=game.Player.Health;game.Turns.TryBeginEnemyTurn();var turn=(System.Collections.IEnumerator)typeof(LanternfallGame).GetMethod("EnemyTurn",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(game,null);while(turn.MoveNext()){}Assert.Less(game.Player.Health,hp);UnityEngine.Object.DestroyImmediate(go);}
        [Test] public void Phase6I1_RangedEnemyReliablyAttacksAlongClearLine(){var go=new GameObject("RangedAttack");var game=go.AddComponent<LanternfallGame>();game.StartRun(10603);var shot=game.Grid.Floors().First(p=>p!=game.Player.Position&&(p.x==game.Player.Position.x||p.y==game.Player.Position.y)&&Mathf.Abs(p.x-game.Player.Position.x)+Mathf.Abs(p.y-game.Player.Position.y)>=2&&Mathf.Abs(p.x-game.Player.Position.x)+Mathf.Abs(p.y-game.Player.Position.y)<=5&&SkillBook.HasLineOfSight(game.Grid,p,game.Player.Position));game.Enemies.Clear();game.Enemies.Add(new EnemyModel(EnemyKind.GloomArcher,shot));game.RefreshPreviews();int hp=game.Player.Health;game.Turns.TryBeginEnemyTurn();var turn=(System.Collections.IEnumerator)typeof(LanternfallGame).GetMethod("EnemyTurn",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(game,null);while(turn.MoveNext()){}Assert.Less(game.Player.Health,hp);UnityEngine.Object.DestroyImmediate(go);}
        [Test] public void Phase6I1_RootsAndWaterCapMovementAtStartOfTurnOnly(){var roots=BiomeCatalog.Get(BiomeId.GloamOrchard);var water=BiomeCatalog.Get(BiomeId.DrownedNarthex);var p=new PlayerModel(PlayerClassId.Gloamstep){Position=new Vector2Int(2,2)};var hazards=new HashSet<Vector2Int>{p.Position};Assert.AreEqual(2,BiomeRules.MoveRange(p,roots,hazards));Assert.AreEqual(3,BiomeRules.MoveRange(p,water,hazards));hazards.Clear();Assert.AreEqual(4,BiomeRules.MoveRange(p,roots,hazards));}
        [Test] public void Phase6I1_BossLaterPhasesHaveIntimidatingButBoundedThreat(){var g=FullGrid(11,11);var boss=new EnemyModel(EnemyKind.LanternWarden,new Vector2Int(5,5));BalanceConfig.ApplyRoomScaling(boss,5);int phase1=EnemyAI.BuildPreview(boss,Vector2Int.zero,g).Count;boss.Health=boss.MaxHealth/2;int phase2=EnemyAI.BuildPreview(boss,Vector2Int.zero,g).Count;Assert.Greater(phase2,phase1);Assert.Less(phase2,g.Floors().Count());Assert.That(EnemyAI.BuildDelayedPreview(boss,Vector2Int.zero,g).Count,Is.GreaterThanOrEqualTo(20));}
        [Test] public void Phase6I1_ProceduralRoomsStayConnectedAndHazardsNeverCreateIslands(){var gen=new RoomGenerator();for(int seed=11000;seed<11040;seed++)for(int room=1;room<=5;room++){var r=gen.Generate(seed,room);Assert.True(gen.IsConnected(r.Grid),$"{seed}/{room}");Assert.True(r.EnemySpawns.All(e=>r.Grid.ShortestPath(r.PlayerSpawn,e,_=>false).Count>0),$"enemy {seed}/{room}");Assert.True(r.HazardTiles.All(r.Grid.IsFloor),$"hazard {seed}/{room}");}}
        [Test] public void Phase6J_HazardIconBoundsUseEqualPaddingAndNeverLeaveTile(){foreach(var size in new[]{24f,48f,96f}){var tile=new Rect(13,17,size,size);var icon=VisualReadability.HazardIconRect(tile);Assert.That(icon.width/tile.width,Is.InRange(.65f,.70f));Assert.AreEqual(icon.height,icon.width,.001f);Assert.AreEqual(icon.xMin-tile.xMin,tile.xMax-icon.xMax,.001f);Assert.AreEqual(icon.yMin-tile.yMin,tile.yMax-icon.yMax,.001f);Assert.True(tile.Contains(icon.min)&&tile.Contains(icon.max));}}
        [Test] public void Phase6J_SquadPlanReservesUniqueDestinationsAndThreatCoverage(){var g=FullGrid(11,11);var player=new Vector2Int(5,5);var enemies=new[]{new EnemyModel(EnemyKind.StoneSentinel,new Vector2Int(2,5)){MoveRange=3},new EnemyModel(EnemyKind.Ashling,new Vector2Int(5,2)){MoveRange=3},new EnemyModel(EnemyKind.Ashling,new Vector2Int(8,5)){MoveRange=3},new EnemyModel(EnemyKind.GloomArcher,new Vector2Int(5,8)){MoveRange=3}};foreach(var e in enemies)EnemyAI.AssignIntent(e,player,g);var plan=EnemyAI.BuildSquadPlan(enemies,player,g,_=>false);Assert.AreEqual(enemies.Length,plan.Destinations.Count);Assert.AreEqual(enemies.Length,plan.Destinations.Values.Distinct().Count());Assert.AreEqual(enemies.Length,plan.AttackTiles.Count);Assert.That(plan.ReservedAttackTiles.Count,Is.GreaterThan(0));Assert.LessOrEqual(plan.Destinations.Values.Count(p=>g.Neighbors(player).Contains(p)),3);}
        [Test] public void Phase6J_SquadSpreadsAcrossFlanksInsteadOfChasingOneLane(){var g=FullGrid(11,11);var player=new Vector2Int(5,5);var enemies=new[]{new EnemyModel(EnemyKind.Ashling,new Vector2Int(1,4)){MoveRange=4},new EnemyModel(EnemyKind.Ashling,new Vector2Int(1,5)){MoveRange=4},new EnemyModel(EnemyKind.StoneSentinel,new Vector2Int(1,6)){MoveRange=4}};var plan=EnemyAI.BuildSquadPlan(enemies,player,g,_=>false);var sides=plan.Destinations.Values.Select(p=>Mathf.Abs(p.x-player.x)>=Mathf.Abs(p.y-player.y)?(p.x>=player.x?0:2):(p.y>=player.y?1:3)).Distinct().Count();Assert.That(sides,Is.GreaterThanOrEqualTo(2),string.Join(",",plan.Destinations.Values));}
        [Test] public void Phase6J_ArcherAvoidsReservedFrontlineTileAndMaintainsRange(){var g=FullGrid(11,11);var player=new Vector2Int(5,8);var tank=new EnemyModel(EnemyKind.StoneSentinel,new Vector2Int(5,3)){MoveRange=3};var archer=new EnemyModel(EnemyKind.GloomArcher,new Vector2Int(4,2)){MoveRange=4};var plan=EnemyAI.BuildSquadPlan(new[]{tank,archer},player,g,_=>false);var front=plan.DestinationFor(tank);var rear=plan.DestinationFor(archer);Assert.AreNotEqual(front,rear);Assert.Greater(Mathf.Abs(rear.x-player.x)+Mathf.Abs(rear.y-player.y),1);Assert.False(Mathf.Abs(front.x-rear.x)+Mathf.Abs(front.y-rear.y)==1,$"tank {front} archer {rear}");}
        [Test] public void Phase6J_SeededEnemyTurnHasNoDestinationCollisions(){for(int seed=12000;seed<12015;seed++){var go=new GameObject("SquadCollision");var game=go.AddComponent<LanternfallGame>();game.StartRun(seed);var before=game.Enemies.Where(e=>e.Alive).ToList();game.Turns.TryBeginEnemyTurn();var turn=(System.Collections.IEnumerator)typeof(LanternfallGame).GetMethod("EnemyTurn",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(game,null);while(turn.MoveNext()){}var positions=game.Enemies.Where(e=>e.Alive).Select(e=>e.Position).ToList();Assert.AreEqual(positions.Count,positions.Distinct().Count(),$"seed {seed}");UnityEngine.Object.DestroyImmediate(go);}}
        [Test] public void Phase6K_TelegraphValidatorFailsClosedAndReportsMismatch(){CombatTelegraphValidator.Reset();var tile=new Vector2Int(2,2);Assert.True(CombatTelegraphValidator.AllowsDamage("visible",tile,new HashSet<Vector2Int>{tile}));LogAssert.Expect(LogType.Error,"TELEGRAPH_MISMATCH source=hidden damageTile=(2, 2) previewCount=1");Assert.False(CombatTelegraphValidator.AllowsDamage("hidden",tile,new HashSet<Vector2Int>{Vector2Int.zero}));Assert.AreEqual(1,CombatTelegraphValidator.MismatchCount);}
        [Test] public void Phase6K_ChargedFloorTelegraphsEveryActualDamageTile(){var g=FullGrid(7,7);var armed=new HashSet<Vector2Int>{new Vector2Int(3,3)};var theme=BiomeCatalog.Get(BiomeId.StormvaultFoundry);var preview=BiomeRules.HazardDamageTiles(theme,g,armed);foreach(var p in g.Floors())Assert.AreEqual(BiomeRules.HazardDamage(theme,p,armed)>0,preview.Contains(p),p.ToString());Assert.AreEqual(5,preview.Count);}
        [Test] public void Phase6K_EmberVentTelegraphMatchesExactDamageTile(){var g=FullGrid(7,7);var armed=new HashSet<Vector2Int>{new Vector2Int(3,3)};var theme=BiomeCatalog.Get(BiomeId.EmberOssuary);var preview=BiomeRules.HazardDamageTiles(theme,g,armed);CollectionAssert.AreEquivalent(armed,preview);foreach(var p in g.Floors())Assert.AreEqual(BiomeRules.HazardDamage(theme,p,armed)>0,preview.Contains(p));}
        [Test] public void Phase6K_AreaSkillsExposePotentialImpactBeforeCasting(){var go=new GameObject("ImpactPreview");var game=go.AddComponent<LanternfallGame>();game.StartRun(12600);game.Enemies.First().Position=game.Grid.Neighbors(game.Player.Position).First();game.SelectSkill(SkillId.CinderBloom);Assert.That(game.ValidTargets.Count,Is.GreaterThan(0));Assert.That(game.PotentialImpactTiles.Count,Is.GreaterThan(game.ValidTargets.Count));foreach(var target in game.ValidTargets)Assert.True(SkillBook.AffectedTiles(game.Grid,target,SkillBook.Get(SkillId.CinderBloom)).All(game.PotentialImpactTiles.Contains));UnityEngine.Object.DestroyImmediate(go);}
        [Test] public void Phase6K_StalledMeleeEnemyBreaksIdleAndClosesDistance(){var g=FullGrid(9,9);var player=new Vector2Int(7,7);var enemy=new EnemyModel(EnemyKind.StoneSentinel,new Vector2Int(1,1)){MoveRange=2,NoProgressTurns=2,PreviousPosition=new Vector2Int(2,1)};var next=EnemyAI.ChooseReposition(enemy,player,g,_=>false);Assert.AreNotEqual(enemy.Position,next);Assert.Less(Mathf.Abs(next.x-player.x)+Mathf.Abs(next.y-player.y),Mathf.Abs(enemy.Position.x-player.x)+Mathf.Abs(enemy.Position.y-player.y));}
        [Test] public void Phase6K_SeededEnemyTurnsNeverTriggerTelegraphMismatch(){for(int seed=12700;seed<12720;seed++){CombatTelegraphValidator.Reset();var go=new GameObject("TelegraphSeed");var game=go.AddComponent<LanternfallGame>();game.StartRun(seed);game.Turns.TryBeginEnemyTurn();var turn=(System.Collections.IEnumerator)typeof(LanternfallGame).GetMethod("EnemyTurn",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(game,null);while(turn.MoveNext()){}Assert.AreEqual(0,CombatTelegraphValidator.MismatchCount,$"seed {seed}");UnityEngine.Object.DestroyImmediate(go);}}

        static GridModel FullGrid(int w,int h){var g=new GridModel(w,h);for(int x=0;x<w;x++)for(int y=0;y<h;y++)g.SetFloor(new Vector2Int(x,y));return g;}
    }
}
